version: 0.1

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 294656644051.dkr.ecr.ap-southeast-1.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t accad5-capstone-ecr .
      - docker tag accad5-capstone-ecr:latest 294656644051.dkr.ecr.ap-southeast-1.amazonaws.com/accad5-capstone-ecr:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 294656644051.dkr.ecr.ap-southeast-1.amazonaws.com/accad5-capstone-ecr:latest

artifacts:
  files:
    - "**/*"
  discard-paths: yes